name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  SelectCommits:
    runs-on: ubuntu-latest
    steps:
      - name: this works right?
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - id: changes
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - name: List changed files
        run: |
          for file in ${{ steps.changes.outputs.changed_files }}; do
              echo "$file was changed"
          done
