name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  identify_changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.toJson.outputs.arr }}
    steps:
      - name: this works right?
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
         fetch-depth: 0
      - id: changes
        run: echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - id: toJson
        run: |
          arr="["
          for file in ${{ steps.changes.outputs.changed_files }}; do
              arr += "$file,"
          done
          arr += "]"
          echo $arr
          echo ${fromJson($arr)}

  build_changes:
    needs: identify_changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ needs.identify_changes.outputs.files }}
    steps:
      - run: echo "${{ matrix.file }} was changed"
